spring:
  application:
    name: "gateway"
  logging:
    file:
      name: logs/application.log
    level:
      root: INFO
      org.springframework: DEBUG
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  config:
    import:
      - classpath:application-redis.yml
      - classpath:application-management.yml
      - classpath:application-mb.yaml

server:
  port: 8081
