spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/chats_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true    # Показывать SQL-запросы в консоли
    database-platform: org.hibernate.dialect.PostgreSQLDialect
